#ifndef ICE__GETTYPEINFO_H
#define ICE__GETTYPEINFO_H
//
#pragma once
//
#ifdef __cplusplus
extern "C" {
#endif
//
#include "devmgr.h"
#include <cfgmgr32.h>
#include <newdev.h>
#include <setupapi.h>
#include "util.h"
//
#pragma comment(lib, "setupapi.lib")
#pragma comment(lib, "newdev.lib")
//
#define FILE_REMOVABLE_MEDIA            0x00000001
#define FILE_READ_ONLY_DEVICE           0x00000002
#define FILE_FLOPPY_DISKETTE            0x00000004
#define FILE_WRITE_ONCE_MEDIA           0x00000008
#define FILE_REMOTE_DEVICE              0x00000010
#define FILE_DEVICE_IS_MOUNTED          0x00000020
#define FILE_VIRTUAL_VOLUME             0x00000040
#define FILE_AUTOGENERATED_DEVICE_NAME  0x00000080
#define FILE_DEVICE_SECURE_OPEN         0x00000100
//
void GetMoreInformation(HDEVINFO, SP_DEVINFO_DATA, const UINT);
void GetDriverName(HWND, const char*);
//
#ifdef __cplusplus
}
#endif
//
#endif